name: CI Workflows

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  initial_checks:
    # Mandatory checks before CI tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: false
      envs: |
        # Code style
        - linux: codestyle

  tests:
    needs: initial_checks
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      display: true
      # Linux PyQt 5.15 and 6.3 installations require apt-getting xcb and EGL deps
      libraries: |
        apt:
          - '^libxcb.*-dev'
          - libxkbcommon-x11-dev
          - libegl1

      envs: |
        # Standard tests
        # Linux builds - test on all supported PyQt5, PyQt6, PySide2 and PySide6 versions and without qtpy
        - linux: py310-test-pyqt515
        - linux: py312-test-pyqt63
        - linux: py311-test-pyqt515
        - linux: py313-test-pyqt68

        - linux: py310-test-pyside515
        - linux: py310-test-pyside63
        - linux: py312-test-pyside68

        - linux: py312-test

        # Test a few configurations on macOS (arm64 is default on macos-14)
        - macos: py310-test-pyqt515
        - macos: py311-test-pyqt515
        - macos: py313-test-pyqt67
        - macos: py310-test-pyqt63
          runs-on: macos-13

        - macos: py310-test-pyside63
        - macos: py311-test-pyside67

        - macos: py310-test

        # Test some configurations on Windows
        - windows: py310-test-pyqt515
        - windows: py312-test-pyqt65
        - windows: py313-test-pyqt68

        - windows: py310-test-pyside515
        - windows: py310-test-pyside65

        - windows: py311-test

        # Try out documentation build on Linux, macOS and Windows
        - linux: py310-docs-pyqt514
          coverage: false
        - linux: py312-docs-pyqt67
          coverage: false
        - macos: py310-docs-pyqt515
          coverage: false
        - windows: py310-docs-pyqt515
          coverage: false

  publish:
    needs: tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      libraries: '^libxcb.*-dev libxkbcommon-x11-dev libgl1 xvfb'
      test_extras: 'test,qt'
      test_command: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & sleep 3; DISPLAY=:99.0 pytest --pyargs echo
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
